#!/bin/sh
clear;
echo "Aguarde enquanto configuro as permissões do /usr/share/nginx/html/$1";
echo "";
chown -R ribafs:nginx /usr/share/nginx/html/$1;
find /usr/share/nginx/html/$1 -type d -exec chmod 775 {} \;
find /usr/share/nginx/html/$1 -type f -exec chmod 664 {} \;
echo "";
echo "Concluído!";

